@baseURL = http://localhost:5000
@urlPath = api/v1
POST {{baseURL}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json

{
    "firstName": "Nguyễn Huy",
    "lastName": "Du 6",
    "email":"nguyenhuydu6@gmail.com",
    "password":"123123123",
    "bYear":"2020",
    "bMonth":"09",
    "bDay":"09",
    "gender":"Nam"
}

###
POST {{baseURL}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json

{
    "emailOrUsername":"nguyenhuydu6@gmail.com",
    "password":"123123123"
}

###
POST {{baseURL}}/{{urlPath}}/refresh-token
Content-Type: application/json
Accept: application/json


###
POST {{baseURL}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json

{
    "email":"dulione19@gmail.com"
}

###
POST {{baseURL}}/{{urlPath}}/reset-password/ada5c7b2cb769052d187e8518a8fd0ea488c6ea14d476cda15838ea26c29411466f98e1744bc805152ad2bfe
Content-Type: application/json
Accept: application/json

{
    "password":"1234567899",
    "confirmPassword":"1234567899"
}


###
POST {{baseURL}}/{{urlPath}}/verify/
Content-Type: application/json
Accept: application/json

{
    "code":586143
}


###
POST {{baseURL}}/{{urlPath}}/change-password
Content-Type: application/json
Accept: application/json

{
   "password":"nguyenhuydu1",
   "confirmPassword":"nguyenhuydu1"
}

###
POST {{baseURL}}/{{urlPath}}/logout
Content-Type: application/json
Accept: application/json


