@baseURL = http://localhost:5000
@urlPath = api/v1
POST {{baseURL}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json

{
    "conversationId": "6857b28eb088794138d98560",
    "receiverId": "684a8b6b6cd3051f3fdedada",
    "textMessage": "ăn cơm chưa",
    "gifUrl": "",
}

### GET CONVERSATION LIST
GET {{baseURL}}/{{urlPath}}/chat/conversation-list
Content-Type: application/json
Accept: application/json


### GET MESSAGES
GET {{baseURL}}/{{urlPath}}/chat/message/67cc505cd8a6a9d3c8086f99
Content-Type: application/json
Accept: application/json

### MARK MESSAGE AS DELETED
DELETE  {{baseURL}}/{{urlPath}}/chat/mark-as-deleted/67cee916967ddf9ec4f82c69/67cc505cd8a6a9d3c8086f99/deleteForEveryOne
Content-Type: application/json
Accept: application/json


### MARK MESSAGE AS READ
PUT  {{baseURL}}/{{urlPath}}/chat/mask-as-read/67cc505cd8a6a9d3c8086f99
Content-Type: application/json
Accept: application/json


### ADD MESSAGE REACTION
PUT  {{baseURL}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json

{
    "conversationId": "67cee916967ddf9ec4f82c65",
    "messageId": "67cef90815b3163ec6490587",
    "reaction": "love",
    "type":"add"
}