@baseURL = http://localhost:5000
@urlPath = api/v1

#CREATE REACT
POST {{baseURL}}/{{urlPath}}/reacts
Content-Type: application/json
Accept: application/json

{
    "type": "love",
    "userTo": "67cbb50c9852e756612b3bb9",
    "postId": "67cc508bd8a6a9d3c8086fad",
    "previousReaction": ""
}

###GET REACTS
GET {{baseURL}}/{{urlPath}}/reacts/684a8ce56cd3051f3fdedb37
Content-Type: application/json
Accept: application/json

###DELETE REACT
DELETE  {{baseURL}}/{{urlPath}}/reacts/67c334793a449356abadbbac/love
Content-Type: application/json
Accept: application/json

