@baseURL = http://localhost:5000
@urlPath = api/v1

### REGISTER 
POST {{baseURL}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json

{
    "firstName": "Lý Thị",
    "lastName": "Thư",
    "email": "lythithu@gmail.com",
    "password": "123123123",
    "bYear": "2004",
    "bMonth": "12",
    "bDay": "03",
    "gender": "Nữ"
}

### LOGIN
POST {{baseURL}}/{{urlPath}}/login
Content-Type: application/json
Accept: application/json

{
    "emailOrUsername":"messipro123@gmail.com",
    "password":"123123123"
}


### REFRESH TOKEN
POST {{baseURL}}/{{urlPath}}/refresh-token
Content-Type: application/json
Accept: application/json

{
   "refreshToken": ""
}


### FORGOT PASSWORD
POST {{baseURL}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json

{
    "email":""
}

###
POST {{baseURL}}/{{urlPath}}/reset-password/:token
Content-Type: application/json
Accept: application/json

{
    "password":"",
    "confirmPassword":""
}


###
POST {{baseURL}}/{{urlPath}}/verify/:verifyToken
Content-Type: application/json
Accept: application/json

{
    "code":586143
}


###
POST {{baseURL}}/{{urlPath}}/change-password
Content-Type: application/json
Accept: application/json

{
   "password":"",
   "confirmPassword":""
}

###
POST {{baseURL}}/{{urlPath}}/logout
Content-Type: application/json
Accept: application/json


