@baseURL = http://localhost:5000
@urlPath = api/v1

### ADD COMMENT
POST {{baseURL}}/{{urlPath}}/comments
Content-Type: application/json
Accept: application/json

{
    "postId":"",
    "content":"",
    "userTo":""
}

### GET COMMENTS
GET  {{baseURL}}/{{urlPath}}/comments/:postId
Content-Type: application/json
Accept: application/json
