@baseURL = http://localhost:5000
@urlPath = api/v1

#CREATE REACT
### type = 'like' | 'love' | 'happy' | 'haha' | 'wow' | 'sad' | 'angry' 
POST {{baseURL}}/{{urlPath}}/reacts
Content-Type: application/json
Accept: application/json

{
    "type": "",
    "userTo": "",
    "postId": "",
    "previousReaction": ""
}

###GET REACTS
GET {{baseURL}}/{{urlPath}}/reacts/:postId
Content-Type: application/json
Accept: application/json

###DELETE REACT
DELETE  {{baseURL}}/{{urlPath}}/reacts/:postId/:previousReaction
Content-Type: application/json
Accept: application/json

